# Generated by Django 3.0.5 on 2021-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotifytoken_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='expire_in',
            new_name='expires_in',
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(max_length=150),
        ),
    ]
